{% set python_min = "3.12" %}
{% set name = "ansible-core" %}
{% set version = "2.20.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a891e5f90cd46626778f0f3d545ec1115840c9b50e8adf25944c5e1748452106

build:
  number: 0
  entry_points:
    - ansible=ansible.cli.adhoc:main
    - ansible-config=ansible.cli.config:main
    - ansible-console=ansible.cli.console:main
    - ansible-doc=ansible.cli.doc:main
    - ansible-galaxy=ansible.cli.galaxy:main
    - ansible-inventory=ansible.cli.inventory:main
    - ansible-playbook=ansible.cli.playbook:main
    - ansible-pull=ansible.cli.pull:main
    - ansible-vault=ansible.cli.vault:main
    - ansible-connection=ansible.cli.scripts.ansible_connection_cli_stub:main
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - setuptools >=45.2.0
    - pip
    - python {{ python_min }}
  run:
    - cryptography
    - jinja2 >=3.1.0
    - packaging
    - python >={{ python_min }}
    - pyyaml >=5.1
    - resolvelib >=0.8.0,<2.0.0
    # https://docs.ansible.com/ansible/latest/user_guide/windows_faq.html#can-ansible-run-on-windows
    - __unix

test:
  imports:
    - ansible
  commands:
    - pip check
    - ansible --help
    - ansible-config --help
    - ansible-console --help
    - ansible-doc --help
    - ansible-galaxy --help
    - ansible-inventory --help
    - ansible-playbook --help
    - ansible-pull --help
    - ansible-vault --help
    - ansible-connection --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://ansible.com/
  summary: Radically simple IT automation
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - pavelzw
    - mariusvniekerk
    - etcet
