{% set name = "ansible-core" %}
{% set version = "2.16.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e4ab559e7e525b1c6f99084fca873bb014775d5ecbe845b7c07b8e9d6c9c048b

build:
  number: 0
  entry_points:
    - ansible=ansible.cli.adhoc:main
    - ansible-config=ansible.cli.config:main
    - ansible-console=ansible.cli.console:main
    - ansible-doc=ansible.cli.doc:main
    - ansible-galaxy=ansible.cli.galaxy:main
    - ansible-inventory=ansible.cli.inventory:main
    - ansible-playbook=ansible.cli.playbook:main
    - ansible-pull=ansible.cli.pull:main
    - ansible-vault=ansible.cli.vault:main
    - ansible-connection=ansible.cli.scripts.ansible_connection_cli_stub:main
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - setuptools >=45.2.0
    - pip
    - python >=3.9
  run:
    - cryptography
    - jinja2 >=3.0.0
    - packaging
    - python >=3.9
    - pyyaml >=5.1
    - resolvelib >=0.5.3,<1.1.0
    # https://docs.ansible.com/ansible/latest/user_guide/windows_faq.html#can-ansible-run-on-windows
    - __unix

test:
  imports:
    - ansible
  commands:
    - pip check
    - ansible --help
    - ansible-config --help
    - ansible-console --help
    - ansible-doc --help
    - ansible-galaxy --help
    - ansible-inventory --help
    - ansible-playbook --help
    - ansible-pull --help
    - ansible-vault --help
    - ansible-connection --help
  requires:
    - pip

about:
  home: https://ansible.com/
  summary: Radically simple IT automation
  license: GPL-3.0-or-later
  license_file: COPYING

extra:
  recipe-maintainers:
    - pavelzw
    - mariusvniekerk
    - etcet
